### PR TITLE
Fix for OSSM-5962

### PR DESCRIPTION
**Pull request by twghu**
Added cipher check.

### CODE REVIEW

**Review by tedjpoole — APPROVED** [review]

**Comment by twghu** [comment]
I've run tests locally outside of the bazel test env and the tests pass.

We can override ?

**Comment by twghu** [comment]
One fix for timeouts I've tested is excluding the timeout sensitive tests from the main batch and running individually at the end.

**Comment by dcillera** [comment]
Decided to override the tests to provide a fixed proxy and to investigate test TIMEOUT issue meanwhile.

**Pull request merged**
