### PR TITLE
Added big-endian support into TestByteOrder

### PR DESCRIPTION
**Pull request by knm3000**
https://github.com/envoyproxy/envoy/pull/22353

### CODE REVIEW

**Comment by oschaaf** [comment]
This LGTM, but I wonder about the following: This is the equivalent of upstream commit https://github.com/envoyproxy/envoy/commit/e834c24e061b710348ffd72016d5d1069698b4ff, right? I suspect that using `cherry-pick` to include that might make the next rebase a tiny fraction easier, and might therefore be preferred.. any thoughts on that? @twghu and/or @dcillera .. any thoughts/preference?

**Review by oschaaf — APPROVED** [review]

**Comment by knm3000** [comment]
Correct, this is the equivalent of upstream commit https://github.com/envoyproxy/envoy/commit/e834c24e061b710348ffd72016d5d1069698b4ff
Let me know if I should remove this maistra commit and make `cherry-pick` instead.

**Comment by jwendell** [comment]
In upstream, backport it to 1.20 and 1.22 branches. Then on the next sync we will get it for free

**Comment by knm3000** [comment]
There is no urgency to backport and include s390x fix for this particular envoy test into 2.2.

**Pull request closed without merging**
