### PR TITLE
[DRAFT] Merge envoy upstream's main branch

### PR DESCRIPTION
**Pull request by oschaaf**
Update the main branch up to and including 9eeee36 (from Oct 18th 2021) from envoyproxy/envoy:main

Please do not merge.

### CODE REVIEW

**Comment by twghu** [comment]
There are some inconsistencies after the local merge.
Can I suggest we break this up possibly week by week to reduce the number of updates ?

**Comment by jwendell** [comment]
@oschaaf I think we can close this one and resume this effort later?

**Comment by oschaaf** [comment]
Good idea — closing

**Pull request closed without merging**
