### PR TITLE
OSSM-1956: a temp. fix for antlr4 crash on s390x

### PR DESCRIPTION
**Pull request by knm3000**
2.3: https://issues.redhat.com/browse/OSSM-1956
2.2: https://issues.redhat.com/browse/OSSM-1526
https://github.com/antlr/antlr4/issues/3728
a permanent fix should replace this one in the future

### CODE REVIEW

**Review by jwendell — APPROVED** [review]
/ok-to-test

**Comment by jwendell** [comment]
Apparently this change was missed during 2.3 rebase?

**Comment by knm3000** [comment]
Correct, this fix is a part of 2.2 and it needs to be added into 2.3

**Comment by jwendell** [comment]
@knm3000 should the title be updated to OSSM-1956?

**Comment by knm3000** [comment]
Updated to OSSM-1956

**Pull request merged**
