### PR TITLE
[maistra-2.0] add backported fixes

### PR DESCRIPTION
**Pull request by oschaaf**
- [x] Depends on https://github.com/maistra/envoy/pull/178 to go in first
- [x] File an issue to re-instate the `UnknownSslAlert` test
- [x] Disable the `ProtocolIntegrationTest.OverflowEncoderBufferFromEncodeDataWithResponseHeadersUnsent` test and file an issue to track fixing it.

-------------

Summary: contains seven backported fixes

- [Add UnknownSslAlert integration test](https://github.com/maistra/envoy/commit/fe4255e103c78064d0e0783e349392f35c34b9bf)
- [Implement handling of escaped slash characters in URL path](https://github.com/maistra/envoy/commit/56abbf7b425c58434024591c2984ca0fd8369bff) 
- [ext-authz: merge duplicate headers from client request in check request](https://github.com/maistra/envoy/commit/82c1576e6261e91723ac2cafd4a6c300dd8760a1)
- [Reject or strip fragment from request URI](https://github.com/maistra/envoy/commit/ce71d8fe3bf0ecc1eef4966178fba44291e535d7)
- [Abort filter chain iteration on local reply](https://github.com/maistra/envoy/commit/0c44f832176549bcbbf892c9e572116f494a97db)
- [decompressors: stop decompressing upon excessive compression ratio](https://github.com/maistra/envoy/commit/1e44506c0749d19339f77273538df74f77efc39c)
- [healthcheck: fix grpc inline removal crashes](https://github.com/maistra/envoy/commit/63b4f86d7bfda75c56807547dde378eacd94d664)

Signed-off-by: Otto van der Schaaf <ovanders@redhat.com>

### CODE REVIEW

**Review by jwendell — APPROVED** [review]

**Comment by oschaaf** [comment]
CI fails with `ERROR: /bazel-cache` .. that seems unrelated to this change?

**Comment by jwendell** [comment]
We need to backport https://github.com/maistra/envoy/pull/153

**Comment by oschaaf** [comment]
> We need to backport #153

Done in https://github.com/maistra/envoy/pull/178

**Comment by oschaaf** [comment]
Allright this will need a little work to get things into proper shape. I think I'll add a commit which:
- Adds the UnknownSslAlert back as disabled, with a TODO to fix the build
- Fix the `ProtocolIntegrationTest.OverflowEncoderBufferFromEncodeDataWithResponseHeadersUnsent`:  the test crashes, and logs this "details: "Didn't find a registered implementation for name: 'encoder-decoder-buffer-filter'". The encoder-decoder-buffer-filter is test-only, perhaps we're not registering it (in the right way).

**Comment by oschaaf** [comment]
Filed https://issues.redhat.com/browse/OSSM-1659 to track resolving the issues mentioned above. For now I added [3abbd4a](https://github.com/maistra/envoy/pull/177/commits/3abbd4ad2b7529470dbd120567c31c8cbfa5968a) which should make CI happy.

**Pull request merged**
