### PR TITLE
OSSM-2150 rebase our changes on top of vanilla upstream 1.24

### PR DESCRIPTION
**Pull request by oschaaf**
Placeholder PR to iterate on landing this & test in CI

### CODE REVIEW

**Comment by oschaaf** [comment]
/test all
(expected to fail)

**Review by jwendell — COMMENTED** [review]
I'm seeing changes in the maistra commit not related to maistra. For instance, directories .github, .azure, docs. Are they a merge leftover?

Also, it seems you grabbed all of our commits and squashed them together. Is that intentional and final? Or this pr is just a draft so you can try the CI?

**Comment by jwendell** [comment]
@oschaaf do you want to disable the failing tests (OSSM-2237 and OSSM-2238) and enable the full build in `run-ci.sh`?

**Comment by oschaaf** [comment]
> @oschaaf do you want to disable the failing tests (OSSM-2237 and OSSM-2238) and enable the full build in `run-ci.sh`?

Yes. 👍

**Review by twghu — APPROVED** [review]
Recommend proceed with merge there are a number of post merge issues requiring addressing.   The main TLS source related classes look ok.   Refer to comment in https://issues.redhat.com/browse/OSSM-2150.

This will not be the final state of for 2.4 as more follow up changes and checks required.

**Pull request merged**
