### PR TITLE
MAISTRA-1934: Support dynamic crypto based on environment

### PR DESCRIPTION
**Pull request by knrc**

### CODE REVIEW

**Review by jwendell — APPROVED** [review]

**Comment by jwendell** [comment]
timeout of 5h :o

**Comment by dmitri-d** [comment]
Looks like the job failure is due to a prow timeout.

**Comment by jwendell** [comment]
This job used to run in ~4h. Now 5h is not enough. I wonder what happened.. our prow k8s cluster just got slower?

Anyway, I'll increase it to 6h. That's just insane :(

**Pull request merged**
