### PR TITLE
Initial work for 2.5

### PR DESCRIPTION
**Pull request by jwendell**
This is based on Dario's branch, plus one commit with a few adjustments to CI scripts and removal of some leftover files from rebase.

### CODE REVIEW

**Comment by jwendell** [comment]
- These envoy prechecks will be go away after this PR is merged, I think. Last commit in this PR removes everything related to them.
- Our CI script only builds Envoy for now. Tests are not running. We should re-enable them in a follow-up PR, when we will fix the failures.

**Comment by jwendell** [comment]
@yxun the tests passed but the job failed at some post action. Can you please take a look?

**Comment by yxun** [comment]
> @yxun the tests passed but the job failed at some post action. Can you please take a look?

What are that set of Github CI jobs ? It looks like in the ci directory. They are triggered by Github or bot

**Comment by yxun** [comment]
"Process did not finish before 10m0s timeout"  we have some timeout limit in cleanup step. The namespace deletion was stuck. Actually, we don't need that step. The deprovision cluster step is enough for cleanup.

**Comment by yxun** [comment]
@jwendell  https://github.com/openshift/release/pull/48228

**Review by twghu — APPROVED** [review]
Ok as initial PR.

**Pull request merged**
