### PR TITLE
WIP: MAISTRA-2242 Cherry-pick https://github.com/envoyproxy/envoy/pull/14884

### PR DESCRIPTION
**Pull request by dgn**
https://github.com/envoyproxy/envoy/pull/14884

### CODE REVIEW

**Comment by dmitri-d** [comment]
Looks like `context_lib` target is missing `cert_validator_lib` depedency (see https://github.com/envoyproxy/envoy/blob/main/source/extensions/transport_sockets/tls/BUILD#L169).

**Comment by dgn** [comment]
> Looks like `context_lib` target is missing `cert_validator_lib` depedency (see https://github.com/envoyproxy/envoy/blob/main/source/extensions/transport_sockets/tls/BUILD#L169).

Thanks! Yeah I initially completely ignored the `BAZEL` files because I had no clue how it works. Thanks to your comment I actually looked into it and I now understand a little bit more I believe. I was also missing a little refactoring to avoid a circular dependency (introduction of `extensions/transport_sockets/tls/stats.h`)

Not sure it'll build now, but it's further then before :slightly_smiling_face: Will go to sleep for now

**Comment by dmitri-d** [comment]
@dgn: do you want me to do the back-port?

**Comment by dgn** [comment]
> @dgn: do you want me to do the back-port?

If you have the time, that would be great, yes. I thought I'll try and see if it's an easy-enough one for me to do it, but obviously it is not

**Pull request closed without merging**
