### PR TITLE
Small changes to adapt to the new main image

### PR DESCRIPTION
**Pull request by jwendell**

### CODE REVIEW

**Review by oschaaf — APPROVED** [review]

**Comment by jwendell** [comment]
Needs this: https://github.com/maistra/test-infra/pull/178

**Comment by oschaaf** [comment]
CI didn't get to  run`WeightedClusterIntegrationTest`, the log tail looks like the build ran out of resources:

```
gcc: fatal error: Killed signal terminated program cc1plus
```

/retest

**Comment by oschaaf** [comment]
To me it looks like CI ran out of resources once more before it got to the test we're interested in. 
Should we reduce the number of bazel --jobs?  Another trick I've observed for reducing memory requirements in CI is manually [splitting the bazel build of the tests and their actual execution](https://github.com/envoyproxy/nighthawk/blob/a911d83f137d226907f7c680cb3225b5a192a0f2/ci/do_ci.sh#L139)

**Pull request closed without merging**
