### PR TITLE
Changes to CI

### PR DESCRIPTION
**Pull request by jwendell**

### CODE REVIEW

**Comment by jwendell** [comment]
`/opt/rh/gcc-toolset-9/root/usr/bin/ld.gold: fatal error: bazel-out/k8-fastbuild/bin/test/extensions/filters/http/router/auto_sni_integration_test: No space left on device` :(

**Comment by oschaaf** [comment]
Allright, so the `WeightedClusterIntegrationTest` no longer fails, which proves that parameterising these tests properly over ipv6/ipv4 was necessary to address the failures we observed . So I'll proceed and mark https://github.com/envoyproxy/envoy/pull/18679 as ready for review in order to propose merging the fix upstream.

**Comment by jwendell** [comment]
@oschaaf cool. Are you going to take a look at the other failures?

**Comment by oschaaf** [comment]
> @oschaaf cool. Are you going to take a look at the other failures?

So looking at the [CI logs for the state of this PR](https://storage.googleapis.com/maistra-prow-testing/pr-logs/pull/maistra_envoy/120/envoy-unit/1453634572217487360/build-log.txt) this PR now fails with:

```
//test/config_test:example_configs_test                                  FAILED in 47.3s
  /bazel-cache/BASE/execroot/envoy/bazel-out/k8-fastbuild/testlogs/test/config_test/example_configs_test/test.log
//test/extensions/key_value/file_based:key_value_store_test              FAILED in 1.4s
  /bazel-cache/BASE/execroot/envoy/bazel-out/k8-fastbuild/testlogs/test/extensions/key_value/file_based/key_value_store_test/test.log
//test/extensions/transport_sockets/tls/integration:ssl_integration_test FAILED in 14.9s
  /bazel-cache/BASE/execroot/envoy/bazel-out/k8-fastbuild/testlogs/test/extensions/transport_sockets/tls/integration/ssl_integration_test/test.log
```

I don't think any of those are related to changes contained in this PR and as such I feel they should not be blocking the merge of this PR. Chances are they occur on the current state of the main branch as well. Having said that, I was looking into what I suspect is the most interesting one, the failing ssl integration test. It was flaking a bit for me on my dev station, but I rebuild with clang/asan and with that it structurally report a double free of what I think is an instance of `Envoy::Extensions::TransportSockets::Tls::CertContext`:
https://gist.github.com/oschaaf/6e4381dd1d24b061d4393e639ac9f773
/cc @twghu 

In any case, I think that maybe we should resolve these failures outside of this PR?

**Comment by jwendell** [comment]
This PR has your fix to the ipv6 failure. I'd rather wait for it to merge upstream then I can submit another PR with the changes from upstream (an update of https://github.com/maistra/envoy/pull/114) plus the fixes for CI.

We want to validate our build image and make sure it is able to build and run the tests in the main branch. Let's make sure these failure are not related to our environment.

**Comment by jwendell** [comment]
Closing this in favor of https://github.com/maistra/envoy/pull/121

**Pull request closed without merging**
