### PR TITLE
Maistra 2.4 sync 2

### PR DESCRIPTION
**Pull request by twghu**
Sync with upstream.

### CODE REVIEW

**Comment by jwendell** [comment]
```
FAIL: //test/integration:tcp_proxy_integration_test
...
./test/integration/server.h:492: Failure
Value of: TestUtility::waitForCounterGe(statStore(), name, value, time_system_, timeout)
  Actual: false (timed out waiting for cluster.cluster_0.upstream_cx_total to be >= 1026)
Expected: true
```

**Comment by twghu** [comment]
Closing as replaced by https://github.com/maistra/envoy/pull/266

**Pull request closed without merging**
